/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsPackageRouteImport } from './routes/docs.$package'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesPackageRouteImport } from './routes/packages.$package'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as DocsPackageIndexRouteImport } from './routes/docs.$package.index'
import { Route as DocsPackagePageRouteImport } from './routes/docs.$package.$page'
import { Route as PackagesPackageIndexRouteImport } from './routes/packages.$package.index'
import { Route as PackagesPackageDemoRouteImport } from './routes/packages.$package.demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPackageRoute = DocsPackageRouteImport.update({
  id: '/$package',
  path: '/$package',
  getParentRoute: () => DocsRoute,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPackageRoute = PackagesPackageRouteImport.update({
  id: '/packages/$package',
  path: '/packages/$package',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPackageIndexRoute = DocsPackageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsPackageRoute,
} as any)
const DocsPackagePageRoute = DocsPackagePageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => DocsPackageRoute,
} as any)
const PackagesPackageIndexRoute = PackagesPackageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesPackageRoute,
} as any)
const PackagesPackageDemoRoute = PackagesPackageDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => PackagesPackageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/$package': typeof DocsPackageRouteWithChildren
  '/packages/$package': typeof PackagesPackageRouteWithChildren
  '/wiki/$slug': typeof WikiSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/docs/$package/$page': typeof DocsPackagePageRoute
  '/packages/$package/demo': typeof PackagesPackageDemoRoute
  '/docs/$package/': typeof DocsPackageIndexRoute
  '/packages/$package/': typeof PackagesPackageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/docs': typeof DocsIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/docs/$package/$page': typeof DocsPackagePageRoute
  '/packages/$package/demo': typeof PackagesPackageDemoRoute
  '/docs/$package': typeof DocsPackageIndexRoute
  '/packages/$package': typeof PackagesPackageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/$package': typeof DocsPackageRouteWithChildren
  '/packages/$package': typeof PackagesPackageRouteWithChildren
  '/wiki/$slug': typeof WikiSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/docs/$package/$page': typeof DocsPackagePageRoute
  '/packages/$package/demo': typeof PackagesPackageDemoRoute
  '/docs/$package/': typeof DocsPackageIndexRoute
  '/packages/$package/': typeof PackagesPackageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/contact'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/$package'
    | '/packages/$package'
    | '/wiki/$slug'
    | '/docs/'
    | '/packages/'
    | '/docs/$package/$page'
    | '/packages/$package/demo'
    | '/docs/$package/'
    | '/packages/$package/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contact'
    | '/sitemap.xml'
    | '/wiki/$slug'
    | '/docs'
    | '/packages'
    | '/docs/$package/$page'
    | '/packages/$package/demo'
    | '/docs/$package'
    | '/packages/$package'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/contact'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/$package'
    | '/packages/$package'
    | '/wiki/$slug'
    | '/docs/'
    | '/packages/'
    | '/docs/$package/$page'
    | '/packages/$package/demo'
    | '/docs/$package/'
    | '/packages/$package/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PackagesPackageRoute: typeof PackagesPackageRouteWithChildren
  WikiSlugRoute: typeof WikiSlugRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$package': {
      id: '/docs/$package'
      path: '/$package'
      fullPath: '/docs/$package'
      preLoaderRoute: typeof DocsPackageRouteImport
      parentRoute: typeof DocsRoute
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$package': {
      id: '/packages/$package'
      path: '/packages/$package'
      fullPath: '/packages/$package'
      preLoaderRoute: typeof PackagesPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$package/': {
      id: '/docs/$package/'
      path: '/'
      fullPath: '/docs/$package/'
      preLoaderRoute: typeof DocsPackageIndexRouteImport
      parentRoute: typeof DocsPackageRoute
    }
    '/docs/$package/$page': {
      id: '/docs/$package/$page'
      path: '/$page'
      fullPath: '/docs/$package/$page'
      preLoaderRoute: typeof DocsPackagePageRouteImport
      parentRoute: typeof DocsPackageRoute
    }
    '/packages/$package/': {
      id: '/packages/$package/'
      path: '/'
      fullPath: '/packages/$package/'
      preLoaderRoute: typeof PackagesPackageIndexRouteImport
      parentRoute: typeof PackagesPackageRoute
    }
    '/packages/$package/demo': {
      id: '/packages/$package/demo'
      path: '/demo'
      fullPath: '/packages/$package/demo'
      preLoaderRoute: typeof PackagesPackageDemoRouteImport
      parentRoute: typeof PackagesPackageRoute
    }
  }
}

interface DocsPackageRouteChildren {
  DocsPackagePageRoute: typeof DocsPackagePageRoute
  DocsPackageIndexRoute: typeof DocsPackageIndexRoute
}

const DocsPackageRouteChildren: DocsPackageRouteChildren = {
  DocsPackagePageRoute: DocsPackagePageRoute,
  DocsPackageIndexRoute: DocsPackageIndexRoute,
}

const DocsPackageRouteWithChildren = DocsPackageRoute._addFileChildren(
  DocsPackageRouteChildren,
)

interface DocsRouteChildren {
  DocsPackageRoute: typeof DocsPackageRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsPackageRoute: DocsPackageRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface PackagesPackageRouteChildren {
  PackagesPackageDemoRoute: typeof PackagesPackageDemoRoute
  PackagesPackageIndexRoute: typeof PackagesPackageIndexRoute
}

const PackagesPackageRouteChildren: PackagesPackageRouteChildren = {
  PackagesPackageDemoRoute: PackagesPackageDemoRoute,
  PackagesPackageIndexRoute: PackagesPackageIndexRoute,
}

const PackagesPackageRouteWithChildren = PackagesPackageRoute._addFileChildren(
  PackagesPackageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PackagesPackageRoute: PackagesPackageRouteWithChildren,
  WikiSlugRoute: WikiSlugRoute,
  PackagesIndexRoute: PackagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
