/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as DocsPackageRouteImport } from './routes/docs.$package'
import { Route as DocsPackageIndexRouteImport } from './routes/docs.$package.index'
import { Route as DocsPackagePageRouteImport } from './routes/docs.$package.$page'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPackageRoute = DocsPackageRouteImport.update({
  id: '/docs/$package',
  path: '/docs/$package',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPackageIndexRoute = DocsPackageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsPackageRoute,
} as any)
const DocsPackagePageRoute = DocsPackagePageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => DocsPackageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/$package': typeof DocsPackageRouteWithChildren
  '/wiki/$slug': typeof WikiSlugRoute
  '/docs/$package/$page': typeof DocsPackagePageRoute
  '/docs/$package/': typeof DocsPackageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/docs/$package/$page': typeof DocsPackagePageRoute
  '/docs/$package': typeof DocsPackageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/$package': typeof DocsPackageRouteWithChildren
  '/wiki/$slug': typeof WikiSlugRoute
  '/docs/$package/$page': typeof DocsPackagePageRoute
  '/docs/$package/': typeof DocsPackageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/contact'
    | '/sitemap.xml'
    | '/docs/$package'
    | '/wiki/$slug'
    | '/docs/$package/$page'
    | '/docs/$package/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contact'
    | '/sitemap.xml'
    | '/wiki/$slug'
    | '/docs/$package/$page'
    | '/docs/$package'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/contact'
    | '/sitemap.xml'
    | '/docs/$package'
    | '/wiki/$slug'
    | '/docs/$package/$page'
    | '/docs/$package/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DocsPackageRoute: typeof DocsPackageRouteWithChildren
  WikiSlugRoute: typeof WikiSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$package': {
      id: '/docs/$package'
      path: '/docs/$package'
      fullPath: '/docs/$package'
      preLoaderRoute: typeof DocsPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$package/': {
      id: '/docs/$package/'
      path: '/'
      fullPath: '/docs/$package/'
      preLoaderRoute: typeof DocsPackageIndexRouteImport
      parentRoute: typeof DocsPackageRoute
    }
    '/docs/$package/$page': {
      id: '/docs/$package/$page'
      path: '/$page'
      fullPath: '/docs/$package/$page'
      preLoaderRoute: typeof DocsPackagePageRouteImport
      parentRoute: typeof DocsPackageRoute
    }
  }
}

interface DocsPackageRouteChildren {
  DocsPackagePageRoute: typeof DocsPackagePageRoute
  DocsPackageIndexRoute: typeof DocsPackageIndexRoute
}

const DocsPackageRouteChildren: DocsPackageRouteChildren = {
  DocsPackagePageRoute: DocsPackagePageRoute,
  DocsPackageIndexRoute: DocsPackageIndexRoute,
}

const DocsPackageRouteWithChildren = DocsPackageRoute._addFileChildren(
  DocsPackageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DocsPackageRoute: DocsPackageRouteWithChildren,
  WikiSlugRoute: WikiSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
