/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SplatRouteImport } from './routes/$'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as DocsPackageRouteImport } from './routes/docs.$package'
import { Route as DocsPackageIndexRouteImport } from './routes/docs.$package.index'
import { Route as DocsPackagePageRouteImport } from './routes/docs.$package.$page'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPackageRoute = DocsPackageRouteImport.update({
  id: '/$package',
  path: '/$package',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPackageIndexRoute = DocsPackageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsPackageRoute,
} as any)
const DocsPackagePageRoute = DocsPackagePageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => DocsPackageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/$package': typeof DocsPackageRouteWithChildren
  '/wiki/$slug': typeof WikiSlugRoute
  '/docs/$package/$page': typeof DocsPackagePageRoute
  '/docs/$package/': typeof DocsPackageIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/docs/$package/$page': typeof DocsPackagePageRoute
  '/docs/$package': typeof DocsPackageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/$package': typeof DocsPackageRouteWithChildren
  '/wiki/$slug': typeof WikiSlugRoute
  '/docs/$package/$page': typeof DocsPackagePageRoute
  '/docs/$package/': typeof DocsPackageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/contact'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/$package'
    | '/wiki/$slug'
    | '/docs/$package/$page'
    | '/docs/$package/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/contact'
    | '/docs'
    | '/sitemap.xml'
    | '/wiki/$slug'
    | '/docs/$package/$page'
    | '/docs/$package'
  id:
    | '__root__'
    | '/$'
    | '/contact'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/$package'
    | '/wiki/$slug'
    | '/docs/$package/$page'
    | '/docs/$package/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WikiSlugRoute: typeof WikiSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$package': {
      id: '/docs/$package'
      path: '/$package'
      fullPath: '/docs/$package'
      preLoaderRoute: typeof DocsPackageRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$package/': {
      id: '/docs/$package/'
      path: '/'
      fullPath: '/docs/$package/'
      preLoaderRoute: typeof DocsPackageIndexRouteImport
      parentRoute: typeof DocsPackageRoute
    }
    '/docs/$package/$page': {
      id: '/docs/$package/$page'
      path: '/$page'
      fullPath: '/docs/$package/$page'
      preLoaderRoute: typeof DocsPackagePageRouteImport
      parentRoute: typeof DocsPackageRoute
    }
  }
}

interface DocsPackageRouteChildren {
  DocsPackagePageRoute: typeof DocsPackagePageRoute
  DocsPackageIndexRoute: typeof DocsPackageIndexRoute
}

const DocsPackageRouteChildren: DocsPackageRouteChildren = {
  DocsPackagePageRoute: DocsPackagePageRoute,
  DocsPackageIndexRoute: DocsPackageIndexRoute,
}

const DocsPackageRouteWithChildren = DocsPackageRoute._addFileChildren(
  DocsPackageRouteChildren,
)

interface DocsRouteChildren {
  DocsPackageRoute: typeof DocsPackageRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsPackageRoute: DocsPackageRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WikiSlugRoute: WikiSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
